### ISSUE TITLE
Erector power disables all building

### ISSUE THREAD

**Issue by SmokeysDev** [Night-Stalkers/ns-scripts#9]
Whenever I get the erector power, I can no longer place any blocks unless I run /toggle_erector to turn it off (tested on standard Build & Shoot client, and OpenSpades)

**Comment by hourai-dev** [comment]
I tried reproducing it on the GHN server but I can build blocks just fine with every level of Erector. Could you give more details about the circumstances in which the bug happens?

**Comment by SmokeysDev** [comment]
Ah this is on the Battle Bots TDM server, when I try to build with that power enabled my block count quickly goes 50 -> 49 -> 50, get a little click sound but no build

**Comment by hourai-dev** [comment]
Okay, I managed to reproduce it. You are right, whenever the Erector power is toggled on, it disables all construction. Will investigate further.

**Comment by hourai-dev** [comment]
Good news, I managed to reproduce it again, this time on my local server. Some updates soon.
